site_name: rebma.io Lab Notebook
theme:
  name: material
  palette: 
    primary: blue
    accent: green
  font:
    text: Open Sans
    code: Fira Mono
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  