copyright: Copyright 2023 Christopher Petrilli (CC BY-SA 4.0)
extra:
  analytics:
    property: XBUPTVHH
    provider: fathom
  social:
    - icon: material/rss-box
      link: https://lab.rebma.io/feed_rss_updated.xml
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/@petrillic
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBNhr5JIXOikgY7ix8xdmSg/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/petrillic
    - icon: fontawesome/brands/github
      link: https://github.com/petrilli/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rebma-io/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/christopher-petrilli-ba391a7/
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - callouts
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:mermaid2.fence_mermaid ""
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/comments.md
        - includes/abbreviations.md
        - includes/glossary.md
  - tables
  - footnotes
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg ""
      emoji_index: !!python/name:materialx.emoji.twemoji ""
nav:
  - Start:
      - index.md
      - changelog.md
  - Projects:
      - projects/index.md
      - Signed GS1 Data Matrix: projects/signed-GS1-data-matrix/
      - Adding Kelvin Clips to LCR Meter: projects/LCR-meter-Kelvin-clips/index.md
      - Replacement Base for Video Microscope: projects/replacement-microscope-base/index.md
      - Decrunching Cheap Telescoping Gauges: projects/decrunching-telescoping-gauges/index.md
  - Electronics:
      - electronics/index.md
      - electronics/fundamentals.md
      - electronics/reference-designators.md
      - electronics/units-of-measure.md
      - electronics/non-intuitive-topics.md
      - electronics/protecting-circuits.md
      - electronics/data-sheets.md
      - Techniques:
          - electronics/soldering.md
          - electronics/simulating-circuits.md
      - Passive Components:
          - electronics/passives/index.md
          - electronics/passives/resistors.md
      - Active Components:
          - electronics/leds.md
          - electronics/sensors.md
      - Circuit Patterns:
          - electronics/filters.md
          - electronics/current-mirror.md
          - electronics/voltage-dividers.md
          - electronics/voltage-multiplier.md
      - PCB:
          - Design: electronics/pcb/design.md
          - Supplier Comparison: electronics/pcb/supplier-comparison.md
      - Fusion 360 for Electronics: electronics/fusion360.md
      - electronics/interesting-parts.md
      - electronics/random-tips-and-tricks.md
      - electronics/manufacturers.md
      - electronics/suppliers.md
  - Mechanical:
      - mechanical/index.md
      - mechanical/fit.md
      - mechanical/screws.md
      - mechanical/tightening-screws-and-bolts.md
      - mechanical/bearings.md
      - mechanical/ip-rating.md
      - mechanical/materials.md
      - mechanical/suppliers.md
  - 3D Stuff:
      - 3d/index.md
      - 3d/joining-parts.md
      - 3d/waterproofing.md
      - Design:
          - Methodology: 3d/design-methodology.md
          - Parametric Modeling: 3d/parametric-parameters.md
          - Fusion 360: 3d/fusion360.md
          - SOLIDWORKS: 3d/solidworks.md
          - Choosing Modeling Tools: 3d/modeling-tools.md
      - Printers:
          - Prusa MINI+: 3d/prusa.md
          - Filament: 3d/filament.md
          - Octoprint: 3d/octoprint.md
      - 3d/my-designs.md
  - Software:
      - software/index.md
      - software/barcode-formats.md
      - Python:
        - software/python/index.md
        - software/python/libraries.md
  - Organization:
      - organization/index.md
      - organization/note-taking.md
      - organization/storage.md
      - organization/sortimo.md
      - organization/labeling.md
      - organization/work-area.md
      - Structure:
          - organization/structure.md
          - organization/inventory.md
          - organization/part-numbers.md
          - organization/product-breakdown-structure.md
      - Random Tips & Tricks: organization/random-tips-and-tricks.md
  - Tools:
      - tools/index.md
      - tools/metrology.md
      - tools/hand-tools.md
      - tools/consumables.md
      - tools/3d-printed-tools.md
      - tools/interesting-tools.md
      - tools/workstation.md
      - Test & Measurement:
          - Tools: tools/test-and-measurement.md
          - tools/using-calipers.md
      - Gadget Guides:
          - tools/guides/index.md
          - Precision I/V Source: tools/guides/precision-voltage-and-current-signal-generator.md
  - Resources:
      - resources/index.md
      - resources/six-step-troubleshooting-method.md
      - resources/books.md
      - resources/blogs-and-websites.md
      - resources/video.md
      - resources/structured-education.md
      - resources/suppliers.md
  - Tags: tags.md
  - About: about.md
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - rss:
      abstract_chars_count: -1
      date_from_meta:
        default_timezone: America/Los_Angeles
      image: https://lab.rebma.io/assets/rebma-io-logo-black.png
  - search:
      lang: en
  - mermaid2:
      arguments:
        securityLevel: loose
  - mknotebooks:
      execute: false
  - glightbox
  - tags:
      tags_file: tags.md
  - table-reader
  - macros:
      include_dir: includes
      j2_block_end_string: "%]]"
      j2_block_start_string: "[[%"
      j2_variable_end_string: "]]"
      j2_variable_start_string: "[["
      module_name: macros
repo_name: rebma-io/lab
repo_url: https://github.com/rebma-io/lab
site_description: A collection fo thoughts and resources for Makers.
site_url: https://lab.rebma.io
archive_url: https://rebma-archive.s3.us-west-000.backblazeb2.com
site_name: lab.rebma.io Notebook
theme:
  custom_dir: overrides
  favicon: assets/rebma-io-logo-black-notext.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - navigation.prune
    - navigation.expand
  font: false
  icon:
    repo: fontawesome/brands/git
  logo: assets/rebma-io-logo-white-notext.png
  name: material
  palette:
    accent: blue
    primary: black
