site_name: rebma.io Notebook
theme:
  name: material
  palette: 
    primary: black
    accent: blue
  font:
    text: Open Sans
    code: Fira Mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - navigation.prune
  icon:
    repo: fontawesome/brands/git
  logo: assets/rebma-io-logo-white.png
  custom_dir: overrides
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - search:
      lang: en
  - mermaid2:
      arguments:
        securityLevel: loose
  - mknotebooks:
      execute: false
  - glightbox
  - macros:
      module_name: macros
      include_dir: includes
      j2_block_start_string: '[[%'
      j2_block_end_string: '%]]'
      j2_variable_start_string: '[['
      j2_variable_end_string: ']]'
repo_url: https://github.com/rebma-io/lab
repo_name: rebma-io/lab
copyright: Copyright 2023 Christopher Petrilli (CC BY-SA 4.0)
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - callouts
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/comments.md
        - includes/abbreviations.md
        - includes/glossary.md
  - tables
  - footnotes
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/@petrillic
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBNhr5JIXOikgY7ix8xdmSg/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/petrillic
    - icon: fontawesome/brands/github
      link: https://github.com/petrilli/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rebma-io/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/christopher-petrilli-ba391a7/
  analytics:
    provider: fathom
    property: XBUPTVHH